// Code generated by MockGen. DO NOT EDIT.
// Source: core.go
//
// Generated by this command:
//
//	mockgen -source=core.go -destination=mock/mock_core.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entities "github.com/internal-transfers-service/internal/modules/account/entities"
	apperror "github.com/internal-transfers-service/pkg/apperror"
	gomock "go.uber.org/mock/gomock"
)

// MockICore is a mock of ICore interface.
type MockICore struct {
	ctrl     *gomock.Controller
	recorder *MockICoreMockRecorder
	isgomock struct{}
}

// MockICoreMockRecorder is the mock recorder for MockICore.
type MockICoreMockRecorder struct {
	mock *MockICore
}

// NewMockICore creates a new mock instance.
func NewMockICore(ctrl *gomock.Controller) *MockICore {
	mock := &MockICore{ctrl: ctrl}
	mock.recorder = &MockICoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICore) EXPECT() *MockICoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICore) Create(ctx context.Context, req *entities.CreateAccountRequest) apperror.IError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(apperror.IError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICoreMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICore)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockICore) GetByID(ctx context.Context, accountID int64) (*entities.AccountResponse, apperror.IError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, accountID)
	ret0, _ := ret[0].(*entities.AccountResponse)
	ret1, _ := ret[1].(apperror.IError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockICoreMockRecorder) GetByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockICore)(nil).GetByID), ctx, accountID)
}
