// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/transaction/core.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/transaction/core.go -destination=internal/modules/transaction/mock/mock_core.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entities "github.com/internal-transfers-service/internal/modules/transaction/entities"
	apperror "github.com/internal-transfers-service/pkg/apperror"
	gomock "go.uber.org/mock/gomock"
)

// MockICore is a mock of ICore interface.
type MockICore struct {
	ctrl     *gomock.Controller
	recorder *MockICoreMockRecorder
	isgomock struct{}
}

// MockICoreMockRecorder is the mock recorder for MockICore.
type MockICoreMockRecorder struct {
	mock *MockICore
}

// NewMockICore creates a new mock instance.
func NewMockICore(ctrl *gomock.Controller) *MockICore {
	mock := &MockICore{ctrl: ctrl}
	mock.recorder = &MockICoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICore) EXPECT() *MockICoreMockRecorder {
	return m.recorder
}

// Transfer mocks base method.
func (m *MockICore) Transfer(ctx context.Context, req *entities.TransferRequest) (*entities.TransferResponse, apperror.IError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, req)
	ret0, _ := ret[0].(*entities.TransferResponse)
	ret1, _ := ret[1].(apperror.IError)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockICoreMockRecorder) Transfer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockICore)(nil).Transfer), ctx, req)
}
